[world]
name = "Token Contracts"
description = "Dojo world hosting ERC-20, ERC-721 and ERC-1155 token contracts backed by OpenZeppelin Cairo components."
seed = "tokens"

[namespace]
default = "tokens"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = ""

[owners]
"tokens" = [
  "tokens-erc20_token",
  "tokens-erc721_token",
  "tokens-erc1155_token",
]

[writers]
"tokens" = [
  "tokens-erc20_token",
  "tokens-erc721_token",
  "tokens-erc1155_token",
]

[init_call_args]
"tokens-erc20_token" = [
  "arr:0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # katana recipients
]

"tokens-erc721_token" = [
  "arr:0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec,0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec,0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # katana recipients
]

"tokens-erc1155_token" = [
  "arr:0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec,0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", # katana recipients
  "arr:1,2", # tokenids
  "arr:3,1", # values (amounts)
]
