[package]
name = "tokens"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"

[dependencies]
dojo = "1.8.0"
starknet = "2.13.1"
openzeppelin_token = "3.0.0"
openzeppelin_introspection = "3.0.0"
openzeppelin_interfaces = "2.1.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = "1.8.0"
